AWSTemplateFormatVersion: '2010-09-09'
Description: 'Backend API stack for Leaguify - API Gateway and Lambda'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)

Resources:
  # S3 Bucket for Avatar Storage
  AvatarBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Environment}-leaguify-avatars-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-leaguify-avatars'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: Leaguify

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: LambdaVPCAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Environment}/leaguify/db/*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub '${AvatarBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Ref AvatarBucket

  # CloudWatch Log Group for Lambda
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Environment}-leaguify-api'
      RetentionInDays: 14
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-leaguify-api-logs'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: Leaguify

  # Lambda function for Express API
  ApiLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaLogGroup
    Properties:
      FunctionName: !Sub '${Environment}-leaguify-api'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Lambda function placeholder. Deploy actual code using serverless or zip file.' })
            };
          };
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
          DB_SSL: 'true'
          AVATAR_BUCKET_NAME: !Ref AvatarBucket
          AWS_REGION: !Ref AWS::Region
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub '${Environment}-Leaguify-PrivateSubnet1Id'
          - Fn::ImportValue: !Sub '${Environment}-Leaguify-PrivateSubnet2Id'
        SecurityGroupIds:
          - Fn::ImportValue: !Sub '${Environment}-Leaguify-LambdaSecurityGroupId'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-leaguify-api'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: Leaguify

  # API Gateway REST API
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${Environment}-leaguify-api'
      Description: Leaguify API Gateway
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-leaguify-api'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: Leaguify

  # API Gateway Resource for /api
  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: api

  # API Gateway Resource for /api/{proxy+}
  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref ApiResource
      PathPart: '{proxy+}'

  # API Gateway Method for ANY /api/{proxy+}
  ProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiLambdaFunction.Arn}/invocations'

  # API Gateway Method for ANY /api
  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiLambdaFunction.Arn}/invocations'

  # Lambda permission for API Gateway
  ApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*'

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ProxyMethod
      - ApiMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref Environment

  # Store avatar bucket name in Parameter Store
  AvatarBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${Environment}/leaguify/avatars/bucket'
      Type: String
      Value: !Ref AvatarBucket
      Description: S3 bucket name for avatar storage

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${Environment}-Leaguify-ApiGatewayUrl'

  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt ApiLambdaFunction.Arn
    Export:
      Name: !Sub '${Environment}-Leaguify-LambdaFunctionArn'

  LambdaExecutionRoleArn:
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${Environment}-Leaguify-LambdaExecutionRoleArn'

  AvatarBucketName:
    Description: S3 bucket name for avatar storage
    Value: !Ref AvatarBucket
    Export:
      Name: !Sub '${Environment}-Leaguify-AvatarBucketName'

  AvatarBucketArn:
    Description: S3 bucket ARN for avatar storage
    Value: !GetAtt AvatarBucket.Arn
    Export:
      Name: !Sub '${Environment}-Leaguify-AvatarBucketArn'
